### ISSUE TITLE
Controller stops working after quitting

### ISSUE THREAD

**Issue by Otaku5371** [HelloThisIsFlo/Deckpad#9] opened 2023-07-10 21:22 UTC
I am currently having an issue where my controller stops working after quitting and isnt detected by my steamdeck in settings either in desktop or gaming mode nor do the track pads work even without steam running

**Comment by Otaku5371** [comment] 2023-07-10 21:29
Running xinput --list the "valve software steam controller" no longer shows up

**Comment by HelloThisIsFlo** [comment] 2023-07-17 16:22
How did you quit Deckpad?

It's possible that `VirtualHere` (the software that captures the controller input and sends them to the network) didn't quit properly and was still capturing input. If that's the case, a simple restart would fix.

Is it fixed on your end now?

**Comment by Otaku5371** [comment] 2023-07-18 17:39
I quit deckpad by tapping on the screen, restarting didnt fix the issue either i had to reinstall the os and that has fixed it

**Comment by HelloThisIsFlo** [comment] 2023-07-19 08:37
Thanks for the update.

I honestly don't know what could have caused this. The only thing I can think of is a bug in the app that I used to capture the controller input (VirtualHere). The Deckpad script itself doesn't capture any input. Now, once this tool (VirtualHere) is closed, it releases the capture. So I have no idea what could have happened.

There probably was a way to fix it without reinstalling the OS, but without being able to reproduce I can't tell.
Since this is fixed on your end, and not reproducible on mine, I'll close the issue. Thanks for reporting

**Closed by HelloThisIsFlo** 2023-07-19 08:37 UTC

**Comment by Sablinova** [comment] 2024-03-04 09:14
this happened to me also
restarting though fixes it until i quit again
