### ISSUE TITLE
Right joystick drift issue

### ISSUE THREAD

**Issue by gleg24** [HelloThisIsFlo/Deckpad#18] opened 2024-05-31 00:56 UTC
When using the right joystick in-game there will be diagonal drift suddenly for about five to ten seconds. This happens every thirty seconds or so. I uploaded an in-game example [here](https://youtube.com/watch?v=VoUuS5ZcFFs) with XDEFIANT, playing on my PC and using the Deck as a controller. It’s important to note that this happens in other games as well, this is just what I recorded it on. It does it whether gyro is enabled or disabled, and also does it with the right trackpad.

**Comment by HelloThisIsFlo** [comment] 2024-05-31 11:19
Hi @gleg24,

Thanks for reporting this issue, and for the supporting video, it's very helpful.

Unfortunately, the issue is not related to Deckpad. All this project does is facilitate the installation/launch of a USB streaming software. 

If there are drift issues, there could be 4 causes I can think of:
- Hardware issues (not very likely if it's only while controlling your PC)
- Issues with the streaming software itself (possible, but I would assume many more people would have similar issues if that was the case)
- **Most likely:** Network issues. Especially if the issue is intermittent, it may be wifi connectivities issues.
- Or maybe, some software running on your PC interfering with the USB streaming software

Since this is not related to Deckpad, I'm closing the issue. I would suggest you try by connecting the PC with cable to the router, and staying close to the router with the steam deck. If the issue is gone ... you know that's the problem. If not ... then it's a bit more tricky. I know how annoying and frustrating these problems can be to debug, so I wish you the best.

If you do find the cause, I would appreciate if you could share, so I can add the info in a FAQ or Troubleshooting section

**Closed by HelloThisIsFlo** 2024-05-31 11:19 UTC
